### ISSUE TITLE
social.technet.microsoft.com

### ISSUE THREAD

**Issue by MeIITek** [Zeeex/Simple-Modern-Dark-Microsoft#1]
Really like using this style, thank you for taking the time to create and maintain it. I am however having an issue when going to any "social.technet.microsoft.com/*" sites as this style shows as loaded however does not change the background to dark and but does change the text to a lighter color in some key areas making a light background with light text unable to read without disabling the style. If you can exclude this site or better yet support the site would be greatly appreciated.

**Comment by Zeeex** [comment]
Thanks for the feedback, I appreciate it.
I've released v1.5 version with some fixes. Try it out. 👍 

Can you send me the link of the affected page, if it still occurs? I'll try to fix it asap.

**Comment by MeIITek** [comment]
Thanks for looking into this. i do see where you have made a change which appears to effect the main site of however pages of the forms are still unreadable with this style enabled. The one page I am looking at today is "https://social.technet.microsoft.com/Forums/windowsserver/en-US/40a4e7ca-bd7c-48be-8e59-456c5d4eb323/runspace-andor-array?forum=winserverpowershell"
if you view this page you will see some of the important text is the same color as the background making it difficult to read some of the key content on this page without disabling or removing this style. 

Edit: I thought I had update the style however it appears I just updated and social.technet.microsoft.com is readable now. 

I also came across another Technet site which this style is effecting in a negative way, blogs.technet.microsoft.com/* page I am looking at right now is "https://blogs.technet.microsoft.com/heyscriptingguy/2015/11/28/beginning-use-of-powershell-runspaces-part-3/"
I like you style and do appreciate you sharing it and would like for you to support these sites as well but if not I understand however could you exclude them so they are not effect.

**Comment by Zeeex** [comment]
I think some script is interfering with microsoft.com domain, I've checked both links and my script doesn't even run there. Check Stylish icon to see which style(script) is loaded.

I'll try to add support for both subdomains in future. :)

**Comment by Zeeex** [comment]
I've updated my style to support blogs and social subdomains.

Please try out new version!
